apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-app
spec:
  replicas: 2
  selector:
    matchLabels:
     app: websocket-app
  template:
    metadata:
      labels:
        app: websocket-app
    spec:
      containers:
      - name: websocket-app
        image: akshayraina/spring-boot-websocket-app:v1.19
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name:  websocket-app
  labels:
    app: websocket-app
spec:
  selector:
    app:  websocket-app
  ports:
    - port: 8081
      targetPort: 8080
      nodePort: 31201
  type:  LoadBalancer